### ISSUE TITLE
USER STORY: View likes

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#10]
As a **site user / admin**  I can **see number of likes on each post** so that **I can see which is the most popular**

## Acceptance Criteria:
* The number of likes will be represented with a heart symbol with the number of likes beside it

## Tasks:
  - [x] Add post likes to post list and post detail views
  - [x] Add to post and detail post html
  - [x] Add font awesome code to display heart symbol
