### ISSUE TITLE
USER STORY: View post list

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#11]
As a **site user**  I can **view a list of posts** so that **i can select one to read**

## Acceptance Criteria:
* The user/ admin can view a list of posts on the home page

## Tasks:
  - [x] Create the view code using Django generic view library
  - [x] Create a template to render the view
  - [x] Connect up the urls in the urls.py file
