### ISSUE TITLE
USER STORY: View number of comments

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#13]
As a **site user/admin**  I can **view how many comments per post** so that **I can see the most popular conversations**

## Acceptance Criteria:
* The user should be able to see how many comments a post has:

## Tasks:
  - [x] Add comment count to model
  - [x] Create the view in post list
  - [x] Update the post list HTML
