### ISSUE TITLE
USER STORY: Post category

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#18]
As a **user**  I can **see a list of categories** so that **I can filter the posts by category**

## Acceptance Criteria:
* Users on large screens can see list of categories in sidebar, not available on screens less than 992px:
* Clicking on a category will filter the post list by the selected category :
* The category filter can be cleared by clicking on "Clear filters":

## Tasks:
  - [x] Create category model
  - [x] Add category to Post model
  - [x] Create post filter view
  - [x] Create category html file
