### ISSUE TITLE
USER STORY: Manage posts

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#3]
As a **site admin**  I can **create, read, update and delete posts** so that **I can manage my blog content**

## Acceptance Criteria:
* Site admin should be able to create a new post.
* Site admin should be able to read all posts.
* Site admin should be able to update all posts.
* Site admin should be able to delete all posts.

## Tasks:
  - [x] Create superuser.
  - [x] Add CRUD functionality into admin.py file.
  - [x] Log in to admin with a superuser account.
  - [x] Test all CRUD functionality.
