### ISSUE TITLE
USER STORY: Open post

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#4]
As a **site user**  I can **cick on a post to open it** so that **I can read the full text and see the comments**

## Acceptance Criteria:
* Site admin / user should be able to click on a post and it will bring them to the page, which will display the entire post

## Tasks:
  - [x] Create generic class based view
  - [x] Create template to render the view
  - [x] connent up the urls in teh urls.py file
