### ISSUE TITLE
USER STORY: Like/Unlike post

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#7]
As a **site user**  I can **like or unlike a post** so that **interact with the content**

## Acceptance Criteria:
* The user should be able to like a post
* The user should be able to unlike a post
* The user should be able to see how many likes a post has

## Tasks:
  - [x] Create the view code
  - [x] Create the view template
  - [x] Connect up urls in urls.py
