### ISSUE TITLE
USER STORY: Site pagination

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/Wild-Atlantic-Way-Blog#8]
As a **site user**  I can **view a paginated lists of posts** so that **I can select a post to view**

## Acceptance Criteria:
* There will be a maximum of four posts per page on post list page:
* User can click on next button to move to next page:
* user can click on previous button to move to previous page:

## Tasks:
  - [x] Update views to add pagination 
  - [x] Create pagination.html
  - [x] Add pagination.html to index.html
